import { beforeEach, describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { Window } from "happy-dom";

/**
 * Behavioural baseline for the shipped player.
 *
 * The player's markup and client script live inside AudioPlayer.astro, which
 * `bun test` cannot import. Rather than test a hand-written copy of the markup --
 * which would drift from the component without anyone noticing -- this runs against
 * genuine Astro build output, regenerated by `bun run fixtures:smoke` and checked for
 * staleness in CI.
 *
 * These tests describe what the player does TODAY, including behaviour that is known
 * to be wrong (see the `known defects` block). They exist so that extracting the
 * engine out of the .astro file can be proven not to change observable behaviour.
 */

const FIXTURE = join(import.meta.dir, "fixtures/smoke/player.html");
const html = readFileSync(FIXTURE, "utf8");

/**
 * Alignment timings for the same fixture the page was built from. Test times are
 * derived from real word boundaries rather than hardcoded: the audio has silence
 * between words, and picking an arbitrary second lands in a gap where no word is
 * active -- which is correct behaviour, not a bug.
 */
const words: Array<{ word: string; start: number; end: number }> = JSON.parse(
  readFileSync(join(import.meta.dir, "fixtures/compat/audio-map.json"), "utf8")
).entries.post.words;

/** A time guaranteed to fall inside the given word's span. */
const midpointOf = (i: number) => (words[i].start + words[i].end) / 2;

interface Harness {
  window: Window;
  document: Document;
  audio: HTMLAudioElement;
  player: HTMLElement;
  q: (sel: string) => HTMLElement | null;
  all: (sel: string) => HTMLElement[];
}

function boot(): Harness {
  const window = new Window({ url: "https://example.test/blog/post/" });
  const document = window.document as unknown as Document;
  document.documentElement.innerHTML = html
    .replace(/^[\s\S]*?<html[^>]*>/i, "")
    .replace(/<\/html>[\s\S]*$/i, "");

  // happy-dom does not run <script> from innerHTML. The fixture generator inlines
  // Astro's hoisted player bundle and marks it, so evaluate exactly that, as the
  // browser would. Failing loudly here matters: a silently un-booted player would
  // make every assertion below meaningless.
  const bundle = document.querySelector("script[data-vocasync-bundle]");
  if (!bundle?.textContent) {
    throw new Error(
      "smoke fixture has no player bundle -- regenerate it with `bun run fixtures:smoke`"
    );
  }
  window.eval(bundle.textContent);

  const player = document.querySelector(".vocasync-player") as HTMLElement;
  const audio = document.querySelector("audio") as HTMLAudioElement;
  return {
    window,
    document,
    player,
    audio,
    q: (sel) => document.querySelector(sel) as HTMLElement | null,
    all: (sel) => Array.from(document.querySelectorAll(sel)) as HTMLElement[],
  };
}

/** The controls region only; the mini player carries duplicate data-action hooks. */
function mainControls(h: Harness): HTMLElement {
  return h.q('[data-state="ready"]') as HTMLElement;
}

function click(h: Harness, el: Element) {
  el.dispatchEvent(new h.window.Event("click", { bubbles: true }) as unknown as Event);
}

let h: Harness;
beforeEach(() => {
  h = boot();
});

describe("initialisation", () => {
  test("renders a player with an audio element", () => {
    expect(h.player).toBeTruthy();
    expect(h.audio).toBeTruthy();
  });

  test("reveals the controls and hides the loading state", () => {
    expect((h.q('[data-state="ready"]') as HTMLElement).hidden).toBe(false);
    expect((h.q('[data-state="loading"]') as HTMLElement).hidden).toBe(true);
    expect((h.q('[data-state="no-audio"]') as HTMLElement).hidden).toBe(true);
  });

  test("sets the audio source and appends the publishable key", () => {
    expect(h.audio.src).toContain("pk=");
  });

  test("wraps article words with alignment indices", () => {
    const words = h.all(".vocasync-word[data-i]");
    expect(words.length).toBeGreaterThan(100);
    expect(words[0].dataset.i).toBe("0");
  });
});

describe("playback", () => {
  test("play button starts playback and swaps to the pause icon", () => {
    const btn = mainControls(h).querySelector('[data-action="play-pause"]') as HTMLElement;
    click(h, btn);
    expect(h.audio.paused).toBe(false);
    expect(btn.getAttribute("aria-label")).toBe("Pause");
    expect(btn.querySelector(".vocasync-icon--play")?.classList.contains("vocasync-hidden")).toBe(
      true
    );
    expect(btn.querySelector(".vocasync-icon--pause")?.classList.contains("vocasync-hidden")).toBe(
      false
    );
  });

  test("clicking again pauses and restores the play icon", () => {
    const btn = mainControls(h).querySelector('[data-action="play-pause"]') as HTMLElement;
    click(h, btn);
    click(h, btn);
    expect(h.audio.paused).toBe(true);
    expect(btn.getAttribute("aria-label")).toBe("Play");
  });

  test("seeking through the progress input moves currentTime", () => {
    const seek = mainControls(h).querySelector('[data-action="seek"]') as HTMLInputElement;
    seek.value = "12.5";
    seek.dispatchEvent(new h.window.Event("input", { bubbles: true }) as unknown as Event);
    expect(h.audio.currentTime).toBeCloseTo(12.5, 3);
  });

  test("the time display follows timeupdate", () => {
    h.audio.currentTime = 65;
    h.audio.dispatchEvent(new h.window.Event("timeupdate") as unknown as Event);
    expect(h.q('[data-time="current"]')?.textContent).toBe("1:05");
  });

  test("choosing a speed sets playbackRate and the label", () => {
    const menu = h.q(".vocasync-player__speed-menu") as HTMLElement;
    click(h, menu.querySelector('[data-speed="1.5"]') as Element);
    expect(h.audio.playbackRate).toBeCloseTo(1.5, 3);
    expect(h.q("[data-speed-label]")?.textContent).toBe("1.5x");
  });

  test("the mute button toggles muted", () => {
    const mute = mainControls(h).querySelector('[data-action="mute"]') as HTMLElement;
    click(h, mute);
    expect(h.audio.muted).toBe(true);
    click(h, mute);
    expect(h.audio.muted).toBe(false);
  });

  test("the volume slider sets volume", () => {
    const vol = mainControls(h).querySelector('[data-action="volume"]') as HTMLInputElement;
    vol.value = "40";
    vol.dispatchEvent(new h.window.Event("input", { bubbles: true }) as unknown as Event);
    expect(h.audio.volume).toBeCloseTo(0.4, 3);
  });
});

describe("word highlighting", () => {
  /** Drive the rAF-based highlighter to a specific time. */
  function seekTo(time: number) {
    h.audio.currentTime = time;
    h.audio.dispatchEvent(new h.window.Event("seeked") as unknown as Event);
  }

  test("marks exactly one word active for a given time", () => {
    const first = h.all(".vocasync-word[data-i]")[0];
    seekTo(midpointOf(0));
    const active = h.all(".vocasync-word.is-active");
    expect(active.length).toBe(1);
    expect(active[0]).toBe(first);
  });

  test("no word is active during silence between words", () => {
    // The audio has real gaps: nothing should be highlighted while no word is being
    // spoken. Find a gap from the timings rather than guessing at a timestamp.
    const gap = words.findIndex((w, i) => i > 0 && w.start - words[i - 1].end > 0.2);
    expect(gap).toBeGreaterThan(0);
    seekTo((words[gap - 1].end + words[gap].start) / 2);
    expect(h.all(".vocasync-word.is-active").length).toBe(0);
  });

  test("the active word advances as time moves forward", () => {
    seekTo(midpointOf(0));
    const early = h.all(".vocasync-word.is-active")[0]?.dataset.i;
    seekTo(midpointOf(40));
    const later = h.all(".vocasync-word.is-active")[0]?.dataset.i;
    expect(Number(later)).toBeGreaterThan(Number(early));
  });

  test("leaves a bounded trail behind the active word", () => {
    seekTo(midpointOf(40));
    const trail = h.all(".vocasync-word.is-trail");
    expect(trail.length).toBeGreaterThan(0);
    expect(trail.length).toBeLessThanOrEqual(4); // trailLength default
  });

  test("the highlight toggle clears and restores highlighting", () => {
    seekTo(midpointOf(40));
    expect(h.all(".vocasync-word.is-active").length).toBe(1);
    const toggle = h.q('[data-action="toggle-highlighting"]') as HTMLElement;
    click(h, toggle);
    expect(h.all(".vocasync-word.is-active").length).toBe(0);
    expect(h.all(".vocasync-word.is-trail").length).toBe(0);
    expect(toggle.getAttribute("data-highlighting")).toBe("off");
    click(h, toggle);
    expect(toggle.getAttribute("data-highlighting")).toBe("on");
  });

  test("clicking a word seeks to its start time", () => {
    const words = h.all(".vocasync-word[data-i]");
    const target = words[20];
    click(h, target);
    expect(h.audio.currentTime).toBeGreaterThan(0);
    expect(h.audio.paused).toBe(false);
  });
});
